### ISSUE TITLE
expo-modules-core error

### ISSUE THREAD

**Issue by yilmazyakut** [PostHog/posthog-react-native#70] opened 2022-09-30 13:32 UTC
Hi,
The error message I got when I followed the posthog integration steps: 

"Error: undefined Unable to resolve module expo-modules-core from ..\app-name\node_modules\expo-application\build\Application.js: expo-modules-core could not be found within the project or in these directories: node_modules"

"react": "17.0.2"
"react-native": "0.66.4"

**Comment by gcho91** [comment] 2022-10-10 17:57
Also posted [here](https://github.com/PostHog/posthog-react-native/issues/69) but installing the expo modules seemed to solve the problem. In order to use expo modules you still need to download the expo modules and Posthog docs wasn't clear on that. `npx install-expo-modules@latest`

https://docs.expo.dev/bare/installing-expo-modules/#automatic-installation

**Comment by SchlagerKhan** [comment] 2022-11-09 13:42
https://github.com/PostHog/posthog-react-native/issues/69#issuecomment-1308781517

**Comment by benjackwhite** [comment] 2022-11-11 14:09
Closing this as the issue is resolved as discussed but also as of v2.2.0 non-expo apps can use alternative more typical dependencies for the native functions we need

**Closed by benjackwhite** 2022-11-11 14:09 UTC
